SELECT CONCAT(NAME, '(', SUBSTR(OCCUPATION,1,1), ')' )
FROM OCCUPATIONS
ORDER BY NAME;


WITH T1 AS (SELECT OCCUPATION, COUNT(OCCUPATION) AS occupation_count
FROM OCCUPATIONS
GROUP BY 1
ORDER BY 2,1 )

SELECT CONCAT('There are a total of', ' ', occupation_count, ' ', LOWER(OCCUPATION), 's.') 
FROM T1