SELECT ROUND(AVG(LAT_N),4)

FROM (SELECT LAT_N,
        ROW_NUMBER() OVER (ORDER BY LAT_N ASC) AS AL,
        ROW_NUMBER() OVER (ORDER BY LAT_N DESC) AS DL
        FROM STATION) AS A
        
WHERE AL IN (DL,DL+1,DL-1)